### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by ryonakamura** [huggingface/pytorch-pretrained-BERT#109]
When I convert a TensorFlow checkpoint in a `pytorch_model.bin` and run `run_classifier.py` with `--bert_model /path/to/pytorch_model.bin` option, following error occurs in `tokenization.py`.

```shell
12/10/2018 18:11:59 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file /Users/MAC/bert/model/uncased_L-12_H-768_A-12/pytorch_model.bin
Traceback (most recent call last):
  File "examples/run_classifier.py", line 637, in <module>
    main()
  File "examples/run_classifier.py", line 480, in main
    tokenizer = BertTokenizer.from_pretrained(args.bert_model, do_lower_case=args.do_lower_case)
  File "/Users/MAC/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 133, in from_pretrained
    tokenizer = cls(resolved_vocab_file, *inputs, **kwargs)
  File "/Users/MAC/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 76, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/Users/MAC/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 51, in load_vocab
    token = reader.readline()
  File "/Users/MAC/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

I noticed that `--bert_model` option is not path to `pytorch_model.bin` file but path to directory containing `pytorch_model.bin` and `vocab.txt`. I close it.

**Comment by kakeith** [comment]
I had the same question/confusion! Thanks for clarifying it should be the path to the directory and not the filename itself.

**Comment by mazicwong** [comment]
Great help, thanks.

**Comment by gongel** [comment]
Thanks
