### ISSUE TITLE
Pretrained Tokenizer Loading Fails: 'PosixPath' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by decodyng** [huggingface/pytorch-pretrained-BERT#110]
I was trying to work through the toy tokenization example from the main README, and I hit an error on the step of loading in a pre-trained BERT tokenizer. 

```
~/bert_transfer$ python3 test_tokenizer.py                                                 
Traceback (most recent call last):
  File "test_tokenizer.py", line 10, in <module>
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "/usr/local/lib/python3.5/dist-packages/pytorch_pretrained_bert/tokenization.py", line 117, in from_pretrained
    resolved_vocab_file = cached_path(vocab_file, cache_dir=cache_dir)
  File "/usr/local/lib/python3.5/dist-packages/pytorch_pretrained_bert/file_utils.py", line 88, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "/usr/local/lib/python3.5/dist-packages/pytorch_pretrained_bert/file_utils.py", line 169, in get_from_cache
    os.makedirs(cache_dir, exist_ok=True)
  File "/usr/lib/python3.5/os.py", line 226, in makedirs
    head, tail = path.split(name)
  File "/usr/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'

(main_env) ubuntu@ip-10-0-0-123:~/datascience/datascience/projects/webcat/bert_transfer$ python3 --version
Python 3.5.2
```

Exact usage in script: 
```
from pytorch_pretrained_bert import BertTokenizer

test_sentence = "When PyTorch first launched in early 2017, it quickly became a popular choice among AI researchers, who found it ideal for rapid experimentation due to its flexible, dynamic programming environment and user-friendly interface"

if __name__ == "__main__":
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')```

I am curious if you're able to replicate this error on python 3.5.2, since the repo states support for 3.5+.

**Comment by thomwolf** [comment]
Ok @hzhwcmhf fixed this issue with #113 and we will be compatible with Python 3.5+ again in the coming release (today probably). Thanks @hzhwcmhf!
