### ISSUE TITLE
AttributeError: 'BertForPreTraining' object has no attribute 'global_step'

### ISSUE THREAD

**Issue by MuruganR96** [huggingface/pytorch-pretrained-BERT#158]
@thomwolf  sir, i am also same issue (https://github.com/huggingface/pytorch-pretrained-BERT/issues/50#issuecomment-440624216). it doen't resolve. how i am convert my finetuned pretrained model to pytorch?

```
export BERT_BASE_DIR=/home/dell/backup/NWP/bert-base-uncased/bert_tensorflow_e100

pytorch_pretrained_bert convert_tf_checkpoint_to_pytorch \
  $BERT_BASE_DIR/model.ckpt-100 \
  $BERT_BASE_DIR/bert_config.json \
  $BERT_BASE_DIR/pytorch_model.bin

```

```
Traceback (most recent call last):
  File "/home/dell/Downloads/Downloads/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/Downloads/Downloads/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dell/backup/bert_env/lib/python3.6/site-packages/pytorch_pretrained_bert/__main__.py", line 19, in <module>
    convert_tf_checkpoint_to_pytorch(TF_CHECKPOINT, TF_CONFIG, PYTORCH_DUMP_OUTPUT)
  File "/home/dell/backup/bert_env/lib/python3.6/site-packages/pytorch_pretrained_bert/convert_tf_checkpoint_to_pytorch.py", line 69, in convert_tf_checkpoint_to_pytorch
    pointer = getattr(pointer, l[0])
  File "/home/dell/backup/bert_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertForPreTraining' object has no attribute 'global_step'
```
sir how to resolve this issue?
thanks.

**Comment by lxy444** [comment]
How do you solve the problem?

**Comment by rpoli40** [comment]
I have the same issue

**Comment by PradyumnaGupta** [comment]
Did you find any solution?

**Comment by Iwazo8700** [comment]
I have the same issue too
