### ISSUE TITLE
how to load checkpoint?

### ISSUE THREAD

**Issue by susht3** [huggingface/pytorch-pretrained-BERT#27]
i download the model from bert, it only has model.ckpt.data，model.ckpt.meta and model.ckpt.index, i donnot which to load, what is checkpoint file for convert.py?

**Comment by susht3** [comment]
Converting TensorFlow checkpoint from ../dataset/bert/uncased_L-12_H-768_A-12/bert_model
Traceback (most recent call last):
  File "convert_tf_checkpoint_to_pytorch.py", line 111, in <module>
    convert()
  File "convert_tf_checkpoint_to_pytorch.py", line 60, in convert
    init_vars = tf.train.list_variables(path)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 95, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 64, in load_checkpoint
    return pywrap_tensorflow.NewCheckpointReader(filename)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 326, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ../dataset/bert/uncased_L-12_H-768_A-12/bert_model

**Comment by danyaljj** [comment]
@susht3 what was your fix?

**Comment by dan-hu-spring** [comment]
I encountered a similar issue and didn't find a solution with ALBERT. I tried using the `export_checkpoint.py` file in ALBERT and sent that into the `convert_tf_checkpoint_to_pytorch` command and there was no error. However the resulting `pytorch.bin` output was unusable :\

**Comment by LysandreJik** [comment]
@dan-hu-spring do you mind opening a new issue with your issue, so that we may take a look?
