### ISSUE TITLE
Issue with apex import on MAC 

### ISSUE THREAD

**Issue by bhoomit** [huggingface/pytorch-pretrained-BERT#314]
Python 3.7
MacOS High Sierra 10.13.6

```
Traceback (most recent call last):
  File "examples/classifier.py", line 1, in <module>
    from pytorch_pretrained_bert.tokenization import BertTokenizer, WordpieceTokenizer
  File "/Users/Bhoomit/work/robin/nlp/pytorch-pretrained-BERT/env/lib/python3.7/site-packages/pytorch_pretrained_bert/__init__.py", line 7, in <module>
    from .modeling import (BertConfig, BertModel, BertForPreTraining,
  File "/Users/Bhoomit/work/robin/nlp/pytorch-pretrained-BERT/env/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 218, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/Bhoomit/work/robin/nlp/pytorch-pretrained-BERT/env/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/Bhoomit/work/robin/nlp/pytorch-pretrained-BERT/env/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/optimizers/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/Bhoomit/work/robin/nlp/pytorch-pretrained-BERT/env/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/optimizers/fp16_optimizer.py", line 8, in <module>
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, THCudaHalfTensor_normall): symbol not found
```

**Comment by thomwolf** [comment]
Unfortunately, apex (and fp16 in general) only work on GPU. So you can't use it on MacOS :/
