### ISSUE TITLE
grad is None in squad example

### ISSUE THREAD

**Issue by vpegasus** [huggingface/pytorch-pretrained-BERT#43]
Hi, guys, I try the `run_squad` example with
```
Traceback (most recent call last):                                                                                                                                                                 | 0/7331 [00:00<?, ?it/s]
  File "examples/run_squad.py", line 973, in <module>
    main()
  File "examples/run_squad.py", line 904, in main
    param.grad.data = param.grad.data / args.loss_scale
AttributeError: 'NoneType' object has no attribute 'data'

```  
I find one of the param.grads is None, so the param.grad.data doesn't exist. 
by the way I down load the data by myself from the urls in this prject. my os is ubuntu 18.04, pytorch 0.41 gpu 1080t

anyone else encounters this situation?  
wanna help, please, thx in advance...

**Comment by thomwolf** [comment]
Oh you're right. I've just fixed that. you can try to pull the current master and test again.

**Comment by vpegasus** [comment]
@thomwolf  it works, thanks
