### ISSUE TITLE
Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by SparkJiao** [huggingface/pytorch-pretrained-BERT#46]
Sorry to bother you
I recently have used your extract_features.py to extract features of some data set but failed. The error information is as follows:
`/opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [11,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "examples/extract_features.py", line 405, in <module>
    main()
  File "examples/extract_features.py", line 375, in main
    all_encoder_layers, _ = model(input_ids, token_type_ids=None, attention_mask=input_mask)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 610, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 328, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 313, in forward
    attention_output = self.attention(hidden_states, attention_mask)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 273, in forward
    self_output = self.self(input_tensor, attention_mask)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 224, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/jiaofangkai/anaconda3/envs/allennlp-env/lib/python3.7/site-packages/torch/nn/functional.py", line 1026, in linear
    output = input.matmul(weight.t())
RuntimeError: cublas runtime error : resource allocation failed at /opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp:333
`
It seems that the index_select function in the models crashed. I read my own data from json files and construct examples from them. I set the batch-size equals 1 and I modified the max_seq_length to the max_length of the input sentences. 
Thanks for your help!

**Comment by thomwolf** [comment]
Your log is very hard to read. Can you format it cleanly?

**Comment by thomwolf** [comment]
It seems like a failed resource allocation.
Maybe you don't have enough RAM or your GPU is too small ?

**Comment by thomwolf** [comment]
Ok feel free to re-open the issue if you still have troubles.

**Comment by zyfedward** [comment]
Hi @SparkJiao 

I met the same issue here, how did you resolve this?

**Comment by nv-quan** [comment]
I have the same issue, did you resolve this? @zyfedward @SparkJiao

**Comment by LysandreJik** [comment]
@nv-quan, do you mind opening a new issue with the template so that we may help?

**Comment by SparkJiao** [comment]
I have forgot how to reproduce the problem but the `index_select` error usually happened due to wrong index. You can use a smaller batch size and run the script on CPU to check the full traceback since the traceback while using GPU is delayed.

**Comment by SparkJiao** [comment]
I have forgot how to reproduce the problem but the `index_select` error usually happened due to wrong index. You can use a smaller batch size and run the script on CPU to check the full traceback since the traceback while using GPU is delayed.
