### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'backward'

### ISSUE THREAD

**Issue by Qzsl123** [huggingface/pytorch-pretrained-BERT#82]
Traceback (most recent call last):                                                                                                                                    | 0/11 [00:00<?, ?it/s] 
  File "examples/run_classifier.py", line 637, in <module>
    main()
  File "examples/run_classifier.py", line 558, in main
    loss.backward()
AttributeError: 'tuple' object has no attribute 'backward'

**Comment by davidefiocco** [comment]
Hi,
Aw, it will be hard for others to help you diagnose that, if you don't include more details about how you ran (i.e. with which parameters) `run_classifier.py`.

**Comment by bheinzerling** [comment]
Looks like there was a code change which changed the forward method of the model involved here from returning a tensor to returning a tuple of tensors. There's probaly a line like
```Python
loss = model(input...)
```
which now needs to be
```Python
loss, something_else = model(input...)
```
